Added ability to decode tokens without verifying them to determine the kid
WebFlight/JWT pull request #2
Opened 2018-10-19 09:08 UTC by Narev

Some Identity providers such as Azure AD use dynamic certificates to sign their tokens. These are references by the keyID (kid) in the jwt. To be able to retrieve the required publickey i added a separate function that just decodes the jwt but does not verify it. 

Additionally i upgraded the project to Mx 7.13.1 as Mx7.12.0 is no longer available in the appstore.

2018-10-19 10:06 UTC, mennodehaas commented
Thanks! I will have a look soon.

2018-10-23 13:41 UTC, mennodehaas requested changes
@Narev please configure entity access in the Mendix project. On startup the modeler displays an error regarding entity access. Rest of your changes are fine. Do you think we need additional unit tests in the project to test the new functionality?

2018-10-24 08:48 UTC, Narev commented
I did not see any entity access issues, however i did notice that the admin did not have the rights to manual test the app. So i provided him with user rights. Additionally i added some unit tests for the new functionality.

2018-10-24 09:50 UTC, mennodehaas approved these changes

2018-10-24 09:51 UTC, merged